# Generated by Django 5.0.4 on 2024-04-06 07:56

import django.db.models.deletion
import newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_rename_category_department_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='department',
            field=models.ForeignKey(default=newsletter.models.default_department, on_delete=django.db.models.deletion.CASCADE, to='newsletter.department'),
        ),
    ]
